### PR TITLE
fix(infra): fix eslint config

### PR DESCRIPTION
**Pull request by marianfoo**
error on build
https://github.com/ui5-community/bestofui5-website/runs/6215944005?check_suite_focus=true
this fixed it for me locally
@petermuessig please have a look at it

### CODE REVIEW

**Comment by petermuessig** [comment]
Hi Marian,

this is no bug. This configuration option is necessary for monorepos as VSCode requires workspace root centric configurations. Hm, I thought it will be ignored as it did locally. But anyhow, when switching back to a single repo this will not be an issue anymore.

Ahh, why does it use the husky hooks. Shouldn't we better disable them for the publishing? I think this is the real issue!

Best regards,
Peter

**Comment by marianfoo** [comment]
If you like you can use #167 to switch to single repo and "fix the bug"

**Comment by petermuessig** [comment]
Ok, I would also disable the husky hooks for the deployment step

**Comment by petermuessig** [comment]
I'll handle this in #167

**Pull request closed without merging**
