### PR TITLE
feat: add new icon for different types

### LINKED ISSUE #223: Add Icons to the types
awesome icons:

brackets-curly --> module

server --> middleware

bars-progress --> task

rectangles-mixed --> customCtronl

snowman-head --> generator

screwdriver --> tooling

browser --> application

### PR DESCRIPTION
**Pull request by marianfoo**
# Changes
- add new awesome icons
- display different icons depending on type:
  - code --> module
  server --> middleware
  bars-progress --> task
  gamepad --> customControl
  robot --> generator
  screwdriver --> tooling
  window-maximize --> application
- display only on desktop

# Test
see changes at: https://marianfoo.github.io/ui5-community.github.io/
image

### CODE REVIEW

**Review by petermuessig — APPROVED** [review]
Basically, I am fine - the gamepad looks a bit weird but anyhow, let's keep it for now.

**Comment by marianfoo** [comment]
@petermuessig 
have a look if you find better ones
You have to filter be "free"

**Comment by tobiasqueck** [comment]
Out of curiosity, why do you need the icons? They provide the same information as the first tag (if I understood correctly) so they don't add informational value. In addition, in my personal opinion, the icon-less page looks nice and sleek, with the icons it looses its sleekness.

Just my two cents...

**Comment by marianfoo** [comment]
hm, yeah i agree, make it at least smaller
the intention was to see the type at a glance

**Pull request merged**
