### PR TITLE
fix(#273): adjust title positioning in firefox

### LINKED ISSUE #273: Title may not be visible in Firefox
Header is not visible in Firefox Browser
Couldn't test that yet cause I don't use that browser

### PR DESCRIPTION
**Pull request by wridgeu**
Heyo,

this should fix #273. Overall somewhat annoying behavior in FF regarding the `display` & `position` props. If there are some CSS  gurus out there, please enlighten me 😅 (I think some of it belongs to how UI5 tries to make it responsive), other than that it should work. 

Example: 
example_ff_sizing

### CODE REVIEW

**Comment by marianfoo** [comment]
Thanks for that. So i don´t need to install FF :D 
I don´t know why the filter test is failling. Can you check please.

You dont need to resize the window like that. Few things only change on startup (like the header)

**Comment by wridgeu** [comment]
> You dont need to resize the window like that. Few things only change on startup (like the header)

Some of the props were overwritten around ~1000ish pixels iirc. that's why I had to pop in an `!important` and resized it like that :D

> I don´t know why the filter test is failling. Can you check please.

Not sure either. From what I could tell locally without `--headless` it just looks wrong(?), did something else change here?

Image from running the test:
image

*Edit: I manually checked ... I guess it should select this (image below), not sure why this got so screwed up and misses by an offset of 1 & 2
image


If I understood that correct theres already the mockserver running in the background hence the resultset on filtering/searching should always be the same, right? Just so that I'm not looking into the wrong direction.

**Comment by marianfoo** [comment]
well, the filter test is very brittle 😖
https://github.com/ui5-community/bestofui5-website/blob/8a2f77ce4bfec4305cc71346b125852d0b7058b6/src/test/e2e/filter.test.js#L32
This test took me way too long to create, might need to speak to the wdi5 wizards
Need to crawl this steep learning curve in wdi5 📈

Deactivated it for now

**Review by marianfoo — APPROVED** [review]
👍

**Comment by wridgeu** [comment]
> well, the filter test is very brittle 😖
> This test took me way too long to create, might need to speak to the wdi5 wizards
> Need to crawl this steep learning curve in wdi5 📈
> Deactivated it for now

I don't blame you. I'm extremely behind when it comes to testing. Eager to learn though. :) Thanks for the approval 🍻

**Comment by marianfoo** [comment]
well the fix was to actually use the mockserver 🙈
https://github.com/ui5-community/bestofui5-website/pull/282/commits/8734b975834423d703f09810bb73ebeed263b888

**Comment by wridgeu** [comment]
> well the fix was to actually use the mockserver 🙈 [8734b97](https://github.com/ui5-community/bestofui5-website/commit/8734b975834423d703f09810bb73ebeed263b888)

... I just saw the commit as well ... 🤣 gr8 discovery, should've looked at that, nice :D - appreciate the info!

**Pull request merged**
