### PR TITLE
refactor: use new icon registry (webc)

### PR DESCRIPTION
**Pull request by wridgeu**
Hi Marian,

I did some minor changes to the timeline view and made use of the new [iconRegistry](https://sap.github.io/ui5-webcomponents/playground/getting-started/using-icons/). I got rid of some of the Promise based logic as I think (but maybe I'm wrong, please correct me!) that this is not needed because everything is required/loaded in onInit (so basically immediately) when opening the view anyway.

Additionally I bumped the version of the types (or rather pushed the package-lock as this was forgotten on 107). I also made some minor adjustments to the Timeline view i.e.: removing unused namespaces and some test function call where a teststring was passed.

PS: I forgot to create a new branch on my fork but that shouldn't get me in trouble :D

BR
Marco

### CODE REVIEW

**Comment by marianfoo** [comment]
Hey, thanks for the pull request.
I wanted to do that for a long time.
But unfortunately I don't see the icons in the timeline locally anymore.
Does it work for you?

Can you please merge the PR so that the merge conflict is fixed.
https://github.com/wridgeu/bestofui5-website/pull/2
Thank you!

**Comment by wridgeu** [comment]
Hey! Odd ... it "worked on my machine" 🤪 -- I'll have a look at it again, probably during the weekend though. I'll go ahead and do the merge then as well. 
Thanks!

**Comment by wridgeu** [comment]
Hi again,

I merged the dependency bump (ty for the PR :P).

I tested the change locally on Chrome, Edge and Firefox with completely emptied out cache + hard refresh as well as in incognito mode. Just to be sure I also deleted the webapp folder and reran everything.

image

Is there any error you observe in the console or maybe network or smth.?

**Comment by marianfoo** [comment]
You´re right, it works in #312 when i deploy it to Azure
Will merge, Thanks!

**Review by marianfoo — APPROVED** [review]

**Pull request merged**
