### PR TITLE
feat: introduce splash screen

### LINKED ISSUE #49: Add loading screen with own bootstrap
maybe with a splash screen or even as PWA

### PR DESCRIPTION
**Pull request by petermuessig**
Fixes #49

### CODE REVIEW

**Review by marianfoo — COMMENTED** [review]
what is the file [O_UI5_V.svg](https://github.com/ui5-community/ui5-community.github.io/pull/94/files#diff-715f2efd773e3b9d8cee0f5fede07f158efbd883dc26fc8d23da131c3727e3d2) for?
depending on dark theme different logo?

**Comment by petermuessig** [comment]
Yes, I was thinking about this - just included the blue and the orange Phoenix into the project for now.

**Comment by marianfoo** [comment]
looks good, will fix #92 first before merge

**Review by marianfoo — CHANGES_REQUESTED** [review]
that´s how it looks when i run it locally
the proper svg size is seen for a split second
splash2

**Comment by marianfoo** [comment]
closed due force push
new PR #150

**Pull request closed without merging**
