### PR TITLE
fix(css): revert infoLabel colors to quartz

### PR DESCRIPTION
**Pull request by marianfoo**

### CODE REVIEW

**Review by petermuessig — APPROVED** [review]
If you really like it better, then go ahead...

**Comment by marianfoo** [comment]
@wridgeu what's you opinion? :)

**Comment by wridgeu** [comment]
Hey @marianfoo, sorry for the WoT - tldr; I think (after some time) the newer version (Pre Fix) makes sense.

At first glance I prefer the the "fixed" version. It seems to be more "readable" in dark mode but maybe badges just aren't supposed to stand out like they did. Then this wouldn't be a valid argument as their appearance is not necessarily less readable but more subtle in newer versions.

So all in all, giving it more time, the newer version (Pre "Fix") looks better as the badges distract less from the content they're supposed to tag. Does that make sense? Sorry if you had to read that 4x. ^^

Pre "Fix" Dark Mode 
image

Post "Fix" Dark Mode
image

**Comment by marianfoo** [comment]
hmmm
i had a look at it in the official samples and i think i agree with you
Plus i am usually an advocate for "Standard", so lets stick to that (for now 🤓)

**Pull request closed without merging**
