### PR TITLE
feat: expand/collapse contributors

### LINKED ISSUE #258: Contributors View collapsed by default
like 
image

### PR DESCRIPTION
**Pull request by marianfoo**
# Changes
- use avatars instead of list in contributors view
- expand and collapse avatars (default collapsed)

### CODE REVIEW

**Comment by marianfoo** [comment]
Hey @petermuessig 
have a look: https://yellow-forest-06ce4fe10-268.centralus.1.azurestaticapps.net/#/contributors
need some better styling

**Review by petermuessig — CHANGES_REQUESTED** [review]
Although it looks technically good, visually I have some feedback:

image

Right now it looks like the name of the contributor is on top. Maybe just hide it for the Avatar list and make it visible with the details. I would use the name of the contributor as tooltip of the Avatar.

**Comment by marianfoo** [comment]
@petermuessig tried my best with my minimal css skills to improve it
have a look now

**Comment by wridgeu** [comment]
Hey @marianfoo 

looks already a _lot_ better! :) 

You know what comes next, right? Dark mode might need a few more tweaks. :D 
image

**other minor things that got my attention are...**

## 1 
I think the full space should be used here or does it lead to a weird look in regards to the spacing between each avatar?
image

## 2
The padding used offsets everything from the "Expand Details" Button position which makes it look a bit off - but maybe I'm just way too picky ^^"
image

If time allows I might try and check some of the changes myself and see if they'd even look good, after all my css skills are limited as well and I am much like yourself not a professional designer :D 

BR :)

**Comment by marianfoo** [comment]
> You know what comes next, right? Dark mode might need a few more tweaks. :D

Ah, damnit, always forget dark mode, good catch.

I put those paddings and margin there on purpose because it was just too tight there.
But you can try out if you find some better layout:
https://github.com/ui5-community/bestofui5-website/blob/5916cb19c00db91307992cbba624b9457b29462a/src/css/style.css#L199-L206

Need to add the `prefers-color-scheme` in there

**Comment by petermuessig** [comment]
Looks awesome +2

**Review by petermuessig — APPROVED** [review]

**Pull request merged**
